version: '3.8'

services:
  coturn:
    image: coturn/coturn:latest
    container_name: crokodial-turn
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf:ro
      - ./data:/var/lib/coturn
    environment:
      - DETECT_EXTERNAL_IP=yes
      - DETECT_RELAY_IP=yes
    command: 
      - turnserver
      - -c
      - /etc/turnserver.conf
    # Uncomment for debugging
    # command:
    #   - turnserver
    #   - -c
    #   - /etc/turnserver.conf
    #   - -v 